clear;clc;
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/coyh4/code/RLCodes/DeepRL-0.3/log/dqn_pixel_atari-180821-171829/19d7d3a4-fca5-41a8-ba5f-f9faeaeef79e.monitor.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/08/22 11:09:22

%% Initialize variables.
% DQN cartpole
%filename = '/Users/andrea/work/4_Projects/DARPA/code/DeepRL-0.3/log/dqn_cart_pole-181006-160126/3a36d477-0d3b-493f-8b4c-ea06000c0f47.monitor.csv';
filename = '/Users/andrea/work/4_Projects/DARPA/code/DeepRL-0.3/log/dqn_cart_pole-181006-160126/4c686e28-8d8e-478e-80d3-6df8e6914125.monitor.csv';

startRow = 3;

%% Format for each line of text:
%   column1: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%11s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Remove white space around all cell columns.
dataArray{1} = strtrim(dataArray{1});

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
data = table;
data.env_id = cellstr(dataArray{:, 1});

%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;
data = table2cell(data);
num_step_interval = 100;
for i = 1:length(data)
    tmpData = data{i};
    idxSep = strfind(tmpData,',');
    reward(i) = str2num(tmpData(1:idxSep(1)-1));
    len(i) = str2num(tmpData(idxSep(1)+1:idxSep(2)-1));
end
lenth_total = cumsum(len);
% window_size = 1;
window_size = 100;
for i = window_size+1:length(data)
    reward_wnd(i-window_size) = mean(reward(i-window_size:i));
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
plot(lenth_total(window_size+1:end),reward_wnd);hold on;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% numPlot = 9000;
% plot(lenth_total(window_size+1:window_size+numPlot),reward_wnd(1:numPlot));hold on;
